import { WordMapping } from '../types/mappingTypes';

export const BASE_NUMBERS = new Map<number, WordMapping>([
  [0, { en: 'zero', ne: 'सुन्ना' }],
  [1, { en: 'one', ne: 'एक' }],
  [2, { en: 'two', ne: 'दुई' }],
  [3, { en: 'three', ne: 'तीन' }],
  [4, { en: 'four', ne: 'चार' }],
  [5, { en: 'five', ne: 'पाँच' }],
  [6, { en: 'six', ne: 'छ' }],
  [7, { en: 'seven', ne: 'सात' }],
  [8, { en: 'eight', ne: 'आठ' }],
  [9, { en: 'nine', ne: 'नौ' }],
  [10, { en: 'ten', ne: 'दश' }],
  [11, { en: 'eleven', ne: 'एघार' }],
  [12, { en: 'twelve', ne: 'बाह्र' }],
  [13, { en: 'thirteen', ne: 'तेह्र' }],
  [14, { en: 'fourteen', ne: 'चौध' }],
  [15, { en: 'fifteen', ne: 'पन्ध्र' }],
  [16, { en: 'sixteen', ne: 'सोह्र' }],
  [17, { en: 'seventeen', ne: 'सत्र' }],
  [18, { en: 'eighteen', ne: 'अठार' }],
  [19, { en: 'nineteen', ne: 'उन्नाइस' }],
  [20, { en: 'twenty', ne: 'बीस' }],
  [21, { en: 'twenty one', ne: 'एक्काइस' }],
  [22, { en: 'twenty two', ne: 'बाइस' }],
  [23, { en: 'twenty three', ne: 'तेइस' }],
  [24, { en: 'twenty four', ne: 'चौबिस' }],
  [25, { en: 'twenty five', ne: 'पच्चिस' }],
  [26, { en: 'twenty six', ne: 'छब्बिस' }],
  [27, { en: 'twenty seven', ne: 'सत्ताइस' }],
  [28, { en: 'twenty eight', ne: 'अठ्ठाइस' }],
  [29, { en: 'twenty nine', ne: 'उनन्तिस' }],
  [30, { en: 'thirty', ne: 'तीस' }],
  [31, { en: 'thirty one', ne: 'एकत्तिस' }],
  [32, { en: 'thirty two', ne: 'बत्तिस' }],
  [33, { en: 'thirty three', ne: 'तेत्तिस' }],
  [34, { en: 'thirty four', ne: 'चौँतिस' }],
  [35, { en: 'thirty five', ne: 'पैँतिस' }],
  [36, { en: 'thirty six', ne: 'छत्तिस' }],
  [37, { en: 'thirty seven', ne: 'सैँतिस' }],
  [38, { en: 'thirty eight', ne: 'अठतिस' }],
  [39, { en: 'thirty nine', ne: 'उनन्चालीस' }],
  [40, { en: 'forty', ne: 'चालीस' }],
  [41, { en: 'forty one', ne: 'एकचालीस' }],
  [42, { en: 'forty two', ne: 'बयालिस' }],
  [43, { en: 'forty three', ne: 'त्रिचालीस' }],
  [44, { en: 'forty four', ne: 'चवालीस' }],
  [45, { en: 'forty five', ne: 'पैँतालीस' }],
  [46, { en: 'forty six', ne: 'छयालीस' }],
  [47, { en: 'forty seven', ne: 'सतचालीस' }],
  [48, { en: 'forty eight', ne: 'अठचालीस' }],
  [49, { en: 'forty nine', ne: 'उनन्चास' }],
  [50, { en: 'fifty', ne: 'पचास' }],
  [51, { en: 'fifty one', ne: 'एकाउन्न' }],
  [52, { en: 'fifty two', ne: 'बाउन्न' }],
  [53, { en: 'fifty three', ne: 'त्रिपन्न' }],
  [54, { en: 'fifty four', ne: 'चवन्न' }],
  [55, { en: 'fifty five', ne: 'पचपन्न' }],
  [56, { en: 'fifty six', ne: 'छपन्न' }],
  [57, { en: 'fifty seven', ne: 'सन्ताउन्न' }],
  [58, { en: 'fifty eight', ne: 'अन्ठाउन्न' }],
  [59, { en: 'fifty nine', ne: 'उनन्साठी' }],
  [60, { en: 'sixty', ne: 'साठी' }],
  [61, { en: 'sixty one', ne: 'एकसट्ठी' }],
  [62, { en: 'sixty two', ne: 'बयसट्ठी' }],
  [63, { en: 'sixty three', ne: 'त्रिसट्ठी' }],
  [64, { en: 'sixty four', ne: 'चौंसट्ठी' }],
  [65, { en: 'sixty five', ne: 'पैंसट्ठी' }],
  [66, { en: 'sixty six', ne: 'छयसट्ठी' }],
  [67, { en: 'sixty seven', ne: 'सतसट्ठी' }],
  [68, { en: 'sixty eight', ne: 'अठसट्ठी' }],
  [69, { en: 'sixty nine', ne: 'उनन्सत्तरी' }],
  [70, { en: 'seventy', ne: 'सत्तरी' }],
  [71, { en: 'seventy one', ne: 'एकहत्तर' }],
  [72, { en: 'seventy two', ne: 'बहत्तर' }],
  [73, { en: 'seventy three', ne: 'त्रिहत्तर' }],
  [74, { en: 'seventy four', ne: 'चौहत्तर' }],
  [75, { en: 'seventy five', ne: 'पचहत्तर' }],
  [76, { en: 'seventy six', ne: 'छयहत्तर' }],
  [77, { en: 'seventy seven', ne: 'सतहत्तर' }],
  [78, { en: 'seventy eight', ne: 'अठहत्तर' }],
  [79, { en: 'seventy nine', ne: 'उनासी' }],
  [80, { en: 'eighty', ne: 'असी' }],
  [81, { en: 'eighty one', ne: 'एकासी' }],
  [82, { en: 'eighty two', ne: 'बयासी' }],
  [83, { en: 'eighty three', ne: 'त्रियासी' }],
  [84, { en: 'eighty four', ne: 'चौरासी' }],
  [85, { en: 'eighty five', ne: 'पचासी' }],
  [86, { en: 'eighty six', ne: 'छयासी' }],
  [87, { en: 'eighty seven', ne: 'सतासी' }],
  [88, { en: 'eighty eight', ne: 'अठासी' }],
  [89, { en: 'eighty nine', ne: 'उनान्नब्बे' }],
  [90, { en: 'ninety', ne: 'नब्बे' }],
  [91, { en: 'ninety one', ne: 'एकान्नब्बे' }],
  [92, { en: 'ninety two', ne: 'बयान्नब्बे' }],
  [93, { en: 'ninety three', ne: 'त्रियान्नब्बे' }],
  [94, { en: 'ninety four', ne: 'चौरान्नब्बे' }],
  [95, { en: 'ninety five', ne: 'पन्चान्नब्बे' }],
  [96, { en: 'ninety six', ne: 'छयान्नब्बे' }],
  [97, { en: 'ninety seven', ne: 'सन्तान्नब्बे' }],
  [98, { en: 'ninety eight', ne: 'अन्ठान्नब्बे' }],
  [99, { en: 'ninety nine', ne: 'उनान्सय' }]
]);

export function createNumberWordMap(): Map<number, WordMapping> {
  return new Map(BASE_NUMBERS);
}
